version: '3.8'

name: inception

# Services
services:
  nginx:
    container_name: nginx
    networks:
    - inception
    env_file: .env
    depends_on:
    - wordpress
    - clay
    - redis
    volumes:
    - wordpress_data:/var/www/html
    build: ./requirements/nginx
    ports:
    - 443:443
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
    - inception
    volumes:
    - wordpress_data:/var/www/html
    env_file: .env
    depends_on:
    - mariadb
    build: ./requirements/wordpress
    restart: on-failure
    expose:
    - "9000"

  mariadb:
    container_name: mariadb
    networks:
    - inception
    volumes:
    - mariadb_data:/var/lib/mysql
    env_file: .env
    build: ./requirements/mariadb
    expose:
    - "3306"
    restart: unless-stopped

  clay:
    container_name: clay
    networks:
    - inception
    build: ./requirements/bonus/clay
    expose:
    - "8081"
    ports:
    - 8081:8081
    restart: on-failure

  adminer:
    container_name: adminer
    networks:
    - inception
    depends_on:
    - mariadb
    build: ./requirements/bonus/adminer
    restart: on-failure
    expose:
    - "8042"

  redis:
    container_name: redis
    networks:
    - inception
    depends_on:
    - wordpress
    volumes:
    - wordpress_data:/var/www/html
    build: ./requirements/bonus/redis
    restart: on-failure
    expose:
    - "6379"
   # ports:
    #- 6379:6379

  portainer:
    container_name: portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    build: ./requirements/bonus/portainer
    restart: always
    ports:
    - 9000:9000
    - 9443:9443

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emadriga/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emadriga/data/mariadb'
  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/emadriga/data/portainer'

networks:
  inception:
    driver: bridge
