CREATE DATABASE IF NOT EXISTS myDB ;
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'aq12wsxz' ;
GRANT ALL PRIVILEGES ON myDB.* TO 'admin'@'%' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;
FLUSH PRIVILEGES;
